name: Replicate Prod to Test

permissions:
  checks: write
  pull-requests: write
  statuses: write

env:
  OVH_OS_ACCESS_PUBLIC_KEY: ${{ secrets.OVH_OS_ACCESS_PUBLIC_KEY }}
  OVH_OS_ACCESS_PRIVATE_KEY: ${{ secrets.OVH_OS_ACCESS_PRIVATE_KEY }}
  OVH_OS_IMAGES_BACKUP_CONTAINER_ENDPOINT: ${{ secrets.OVH_OS_IMAGES_BACKUP_CONTAINER_ENDPOINT }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
  BLOB_READ_WRITE_TOKEN_TEST: ${{ secrets.BLOB_READ_WRITE_TOKEN_TEST }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  DATABASE_NAME_TEST: ${{ secrets.DATABASE_NAME_TEST }}
  DATABASE_URI: ${{ secrets.DATABASE_URI }}
  DATABASE_URI_TEST: ${{ secrets.DATABASE_URI_TEST }}
  BACKUP_RESTORE_PREFIX: ${{ secrets.BACKUP_RESTORE_PREFIX }}

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "YES REPLICATE" to confirm replication. CAUTION: THIS CAN NOT BE UNDONE!'
        required: true

jobs:
  restore:
    if: ${{ github.event.inputs.confirm == 'YES REPLICATE' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Install & Setup mongodb-tools
        run: |
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.6.1.deb
          sudo apt install ./mongodb-database-tools-*-100.6.1.deb

      - name: Replicate
        run: npm run replicate:prod
        env:
          CI: true

